### ISSUE TITLE
Email Branding

### ISSUE THREAD

**Issue by hnla** [paulgibbs/BuddyPress#14]
It occurred to me that the first suggestions that will arise will be how to add site branding to the emails.

To this end I'm experimenting in a new branch and have added and testing a new control in the header section to add an image, initially this is a simple option to select from media library and have the image aligned across the top, and due to the boring varied client handling of images will be an img tag and link back (recipient can decide whether their client shows these or not )

I'll probably add a checkbox to allow disabling of the site name string, later that could be extended to have the site name act as a positioned overlay on the image quite easily.

This initial implementation is simple and should extensible  without causing any issues  if already in use.

**Comment by paulgibbs** [comment]
@hnla Check out @timersys plugin which the Customizer implementation (and email templating, and much more) was based on: https://wordpress.org/plugins/email-templates/

He built in images for the header but I stripped it out for simplicity.

Definitely something we should maybe do, probably not for v1.

**Comment by hnla** [comment]
Oh ok I won't pursue further then.

I do agree with the principle generally of releasing base implementations and building on them with subsequent releases, it's just with this aspect I know the immediate request will be to be able to brand emails, it's almost the primary thing required in many senses.
