### ISSUE TITLE
Emails: emogrifier library requires PHP >= 5.4

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/BuddyPress#3]
The `emogrifier` library requires PHP >= 5.4 (and the next major version will require 5.5+).

BuddyPress supports back to 5.2, like WordPress, so I don't know what to do here. @timersys, what's emogrifier used for? Do you think we can make do without it (what can't we do without it?)? Do we need to write a custom fork for 5.2 compat? Or use something else?

**Comment by timersys** [comment]
Upps I missed that one. Someone commented on the trac that we could use emogrifier as woocommerce and I implemented it without checking. Not sure if [they are using the latest version](https://github.com/woothemes/woocommerce/blob/master/includes/libraries/class-emogrifier.php) but I can check next week.

It's really used to convert css into inline styles. On my original plugin [I simple used variables](https://github.com/timersys/wordpress-email-templates/blob/master/admin/templates/partials/header.php) to do that, but writing is more clear and readable to be honest.

**Comment by paulgibbs** [comment]
I think they are using some pre-0.1 commit before namespaces were introduced; I was tempted to do something similar but don't know if forking/maintaining this is something I want to do.

**Comment by paulgibbs** [comment]
https://github.com/woothemes/woocommerce/commit/ea908283a3ea661bc01e7df86b04b8427a280e6c#diff-afd1274ee528a58995932583237c1dcc

**Comment by paulgibbs** [comment]
I just had a thought that if the stuff-css-in-the-email-template operation can be done in one of our grunt-build tasks, it doesn't matter if it requires newer PHP.

**Comment by timersys** [comment]
If grunt does that will be great but will let users change css ?

**Comment by paulgibbs** [comment]
Decided to keep. this simple like your original implementation (just insert the relevant CSS into the email template). Thanks for the discussion here.
