### ISSUE TITLE
Emails: many questions

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/BuddyPress#4]
@timersys I had the feeling I'm going to have a lot of questions about the code so opening this ticket for all of them. If you could quote the question when you reply, that will help us track the conversation. Thanks.

**Comment by paulgibbs** [comment]
What's the difference between customizer-front.js and customiser-admin.js? `front` looks like it registers all the controls for the page, and is `admin` for further customisations to the customizer? For example, hooking up the "send email" button?

**Comment by paulgibbs** [comment]
Why does `bp_core_customizer_remove_all_actions` need to happen? What problems did you find not doing that?

**Comment by timersys** [comment]
> What's the difference between customizer-front.js and customiser-admin.js?

Because the way customizer works you need to hook into two different actions.  customizer-front.js will affect only the right part of the screen ( front live preview) while the other bit is for the admin part ( sidebar with all the options)

**Comment by timersys** [comment]
> Why does bp_core_customizer_remove_all_actions need to happen? What problems did you find not doing that?

Basically I in preview (customizer mode) you need to print scripts so I have this:
`<?php if( is_customize_preview() ) wp_footer();?>`

As many plugins hooks to footer I found easier just to remove everything except what I need just to be safe. Im sure there is a better way to do this, what do you think?

**Comment by paulgibbs** [comment]
>> Why does bp_core_customizer_remove_all_actions need to happen? What problems did you find not doing that?
> Basically I in preview (customizer mode) you need to print scripts so I have this:
`<?php if( is_customize_preview() ) wp_footer();?>`
> 
> As many plugins hooks to footer I found easier just to remove everything except what I need just to be safe. Im sure there is a better way to do this, what do you think?

Did you choose to remove as a precaution or did you find a plugin that actually caused a problem? I'm just trying to understand the decision here, I can understand why it *might* need to be done.

**Comment by timersys** [comment]
> Did you choose to remove as a precaution or did you find a plugin that actually caused a problem? I'm just trying to understand the decision here, I can understand why it might need to be done.

I did find some problems. There are a lot of plugins that prints html in wp_footer like popups plugins, etc.

**Comment by paulgibbs** [comment]
>> Did you choose to remove as a precaution or did you find a plugin that actually caused a problem? I'm just trying to understand the decision here, I can understand why it might need to be done.
> I did find some problems. There are a lot of plugins that prints html in wp_footer like popups plugins, etc.

Thanks. I think I'm going to remove it for now and see what issues we run into. I suspect the real solution is that other plugins that insert stuff like this should be checking for `is_preview` and/or `is_customize_preview` themselves. But we can re-instate if testing proves this to be a big hassle.

**Comment by timersys** [comment]
> Thanks. I think I'm going to remove it for now and see what issues we run into. I suspect the real solution is that other plugins that insert stuff like this should be checking for is_preview and/or is_customize_preview themselves. But we can re-instate if testing proves this to be a big hassle.

Just think that the customizer is really meant for changing the front end. We are the ones using it for a different purpose, I think is too much to ask every plugin that prints html in wp_footer to use is_preview when they really don't need to.

**Comment by paulgibbs** [comment]
Hi @timersys, hope you're well.

I noticed in your plugin's readme.txt you state a minimum required version of WP 4.0 -- is that when the Customizer was introduced, or was some function introduced that we rely on?

**Comment by timersys** [comment]
Some functions were [added](https://make.wordpress.org/core/2014/07/08/customizer-improvements-in-4-0/). On top of my head it was add_panel that I used. Not sure which other as I coded the plugin after 4.0 so I used everything available in the docs but checking this link I think add_panel is the only one.

**Comment by paulgibbs** [comment]
Thanks!
